"""Differentiable audio EoT and explicit evaluation-only channel adapters."""

from transforms.eot import (
    CodecEvaluationAdapter,
    EoTCompose,
    EOTCompose,
    EvaluationBackendRequiredError,
    EvaluationTransformAdapter,
    NoiseTransform,
    NonDifferentiableTransformError,
    PlaybackEvaluationAdapter,
    RIRTransform,
    ResampleTransform,
    add_noise,
    additive_noise,
    add_white_noise,
    apply_rir,
    apply_room_impulse_response,
    codec_roundtrip,
    eot_loss,
    expectation_over_transforms,
    playback_capture,
    resample,
    resample_waveform,
    rir_convolution,
)

__all__ = [
    "CodecEvaluationAdapter",
    "EoTCompose",
    "EOTCompose",
    "EvaluationBackendRequiredError",
    "EvaluationTransformAdapter",
    "NoiseTransform",
    "NonDifferentiableTransformError",
    "PlaybackEvaluationAdapter",
    "RIRTransform",
    "ResampleTransform",
    "add_noise",
    "additive_noise",
    "add_white_noise",
    "apply_rir",
    "apply_room_impulse_response",
    "codec_roundtrip",
    "eot_loss",
    "expectation_over_transforms",
    "playback_capture",
    "resample",
    "resample_waveform",
    "rir_convolution",
]
